### ISSUE TITLE
Performance improvement for xlsx parser

### ISSUE THREAD

**Issue by Shimuuar** [qrilka/xlsx#100]
This is rather vague and open ended. But it would be very nice to improve performance of parser. Parsing of large documents (thousands of rows, >1MB in file size) takes tens of seconds. It would be very nice to improve performance. 

I'm filing this issue as catch-all for further discussion.

**Comment by qrilka** [comment]
It appears that the main slowness comes form xml parsing with `xml-conduit` and my current idea is try out switching to `hexpat` though such move would be quite an effort.

**Comment by qrilka** [comment]
It appears that SAX interface of `xml-conduit` gives quite a good performance but that means that parsing needs to be changed. I suppose that changing worksheet parsing should be enough so existing code using `ToElement`/`FromCursor` could stay used for not large xml files.
@Shimuuar could you give some real-life large xlsx files so I could check them out and use for tests?

**Comment by Fuuzetsu** [comment]
@qrilka Find below an example XLSX file: it is merely 26 columns with single character in them copied down 6000 rows. When I was profiling `xlsx`, at the point of `xml-conduit:parseLBS` it was using nearly 800MB of memory and took 30 seconds (with profiling and heap profiling on mind you). I have experimented before with other parsers: `hexpat` results in even worse memory usage (`.Extended` used 1.1GB and `.Tree` used about the same as `xml-conduit` but is not as feature complete: it does not have comment locations for example; this is OK for us but probably not OK in general for `xlsx`). It was much faster however: I forgot to write down how much... but it was very significant. `hexml` was 2x as fast as `hexpat` and only used 13MB of memory but it's not feature complete at all and likely can't be used for `xlsx` at all. There's also `puglxml` with Haskell bindings which I have heard good things about but have not tried. For us we do not care that much about perfect XLSX parsing to the point where `render . parse ~ id` so I am thinking about implementing just the subset of the functionality we need with hexml or something similar. Nevertheless if `xlsx` can improve the parsing performance, that would be the best for everyone of course.

[6000 rows x 26 cols.xlsx](https://github.com/qrilka/xlsx/files/1410511/6000.rows.x.26.cols.xlsx)

**Comment by qrilka** [comment]
thanks for your report and file @Fuuzetsu , my preliminary tests of SAX parser show quite good numbers but as parsing of quite a lot of details needs to be ported it takes some time. Probably I should work on porting cell  parsing measure the result so it will be clear if the direction I choose is a good one.

**Comment by Fuuzetsu** [comment]
@qrilka do you have any idea about time that will be needed? days, weeks, months? Would like to know if we should invest time alternatives for medium-term.

**Comment by qrilka** [comment]
I hope that I could get at least cell parsing and some estimates later this week and if the numbers will be OK the process will be almost mechanical (though e.g. I found 1 bug in data validation parsing already) so I should be able to get it done next week

**Comment by qrilka** [comment]
@Fuuzetsu @Shimuuar unfortunately it appears that my hope was from a fault in my benchmarks. The result was no good at all.
So in the end I created https://github.com/qrilka/sheet-parsing-tests to track my benchmarking efforts and both `xml-conduit` and `hexpat` are way too slow, using worksheet from the xlsx above on my machine I see:
```
benchmarking cell parsing/with xml-conduit/stream
time                 3.303 s    (3.221 s .. 3.369 s)
                     1.000 R²   (1.000 R² .. 1.000 R²)
mean                 3.321 s    (3.302 s .. 3.335 s)
std dev              20.45 ms   (0.0 s .. 23.49 ms)
variance introduced by outliers: 19% (moderately inflated)
             
benchmarking cell parsing/with xml-conduit/cursor
time                 4.686 s    (4.294 s .. NaN s)
                     0.999 R²   (0.996 R² .. 1.000 R²)
mean                 4.719 s    (4.617 s .. 4.773 s)
std dev              88.75 ms   (0.0 s .. 93.48 ms)
variance introduced by outliers: 19% (moderately inflated)
             
benchmarking cell parsing/with hexpat/tree
time                 2.568 s    (2.322 s .. 2.688 s)
                     0.999 R²   (0.997 R² .. 1.000 R²)
mean                 2.582 s    (2.544 s .. 2.607 s)
std dev              37.08 ms   (0.0 s .. 42.78 ms)
variance introduced by outliers: 19% (moderately inflated)
             
benchmarking cell parsing/with hexpat/SAX
time                 2.080 s    (2.072 s .. 2.085 s)
                     1.000 R²   (1.000 R² .. 1.000 R²)
mean                 2.078 s    (2.077 s .. 2.079 s)
std dev              1.439 ms   (0.0 s .. 1.634 ms)
variance introduced by outliers: 19% (moderately inflated)
```
so in result even SAX with hexpat is just slightly than 2 times faster than the current mechanism of `xlsx`.
Tomorrow I want to try `hexml`.
Or maybe I do something bad in my parsing - please let me know if you notice something.

**Comment by Fuuzetsu** [comment]
2x is much better than 0. How is memory looking? 

Unsure if hexml is sufficient feature wise, it's very minimal...

**Comment by qrilka** [comment]
For smaller file I get the following numbers with `weigh`:
```
Case                       Allocated  GCs
with xml-conduit/stream  397,868,016  761
with xml-conduit/cursor  416,092,256  798
with hexpat/tree         115,942,392  222
with hexpat/SAX          126,484,608  243
```
larger memory consumption of hexpat/SAX is probably due to not quite best code in that example fiddling with lazy list of SAX events. And overall SAX variant looks to be too error-prone to be worth 20% difference (and for larger parsing code it could get even smaller). That probably could be improved by using arranging some neater interface for hexpat SAX like what `Text.XML.Stream.Parse` provides.
Regarding `hexml` - I'm not sure that `xlsx` needs strict XML validation the main point could be in entities expanding but that could be done in an extra postprocessing step when and if text values are needed (e.g. in theory you could get XML entities as a part of some numeric value but in practice I think such a case could be ignored).
So as the next step I'll test `hexml`.

**Comment by Fuuzetsu** [comment]
Awesome, keep us updated!

**Comment by qrilka** [comment]
So the latest results look like:
```
benchmarking cell parsing/with xml-conduit/stream
time                 158.5 ms   (157.8 ms .. 159.2 ms)
                     1.000 R²   (1.000 R² .. 1.000 R²)
mean                 159.8 ms   (159.3 ms .. 160.4 ms)
std dev              778.0 μs   (557.5 μs .. 1.025 ms)
variance introduced by outliers: 12% (moderately inflated)
             
benchmarking cell parsing/with xml-conduit/cursor
time                 237.7 ms   (225.4 ms .. 252.9 ms)
                     0.999 R²   (0.995 R² .. 1.000 R²)
mean                 240.8 ms   (235.2 ms .. 245.6 ms)
std dev              5.728 ms   (2.599 ms .. 8.001 ms)
variance introduced by outliers: 16% (moderately inflated)
             
benchmarking cell parsing/with hexpat/tree
time                 116.9 ms   (112.4 ms .. 119.9 ms)
                     0.999 R²   (0.997 R² .. 1.000 R²)
mean                 118.6 ms   (117.3 ms .. 119.8 ms)
std dev              1.777 ms   (1.155 ms .. 2.762 ms)
variance introduced by outliers: 11% (moderately inflated)
             
benchmarking cell parsing/with hexpat/SAX
time                 105.5 ms   (101.8 ms .. 107.8 ms)
                     0.999 R²   (0.996 R² .. 1.000 R²)
mean                 105.8 ms   (104.3 ms .. 107.2 ms)
std dev              2.210 ms   (1.526 ms .. 3.240 ms)
             
benchmarking cell parsing/with hexml
time                 36.11 ms   (35.98 ms .. 36.21 ms)
                     1.000 R²   (1.000 R² .. 1.000 R²)
mean                 36.43 ms   (36.30 ms .. 36.68 ms)
std dev              341.7 μs   (178.5 μs .. 538.6 μs)
             
benchmarking cell parsing/with xeno/DOM
time                 42.98 ms   (42.81 ms .. 43.20 ms)
                     1.000 R²   (1.000 R² .. 1.000 R²)
mean                 42.73 ms   (42.60 ms .. 42.87 ms)
std dev              247.0 μs   (192.7 μs .. 323.0 μs)
             
Benchmark bench: FINISH
Benchmark weigh: RUNNING...
             
Case                       Allocated  GCs
with xml-conduit/stream  389,210,568  747
with xml-conduit/cursor  411,893,672  792
with hexpat/tree         112,494,176  216
with hexpat/SAX          123,230,920  237
with hexml                67,785,400  130
with xeno/DOM             89,574,128  165
```
So the difference between the current `xml-conduit` cursor approach and `hexml` parsing is about 6 times. At the same as `hexml` is not quite XML-compliant I think it could make sense to add `toXlsxFast` function which will use `hexml` for sheet parsing (with entities decoding added). From the other side that would mean almost 2 times more parsing code and also need to keep hexml/xml-conduit parsing in sync.
Do you have any opinion on that @Shimuuar , @Fuuzetsu ?

**Comment by Fuuzetsu** [comment]
Are these numbers for the same XLSX as the ones above or the smaller sheet you mentioned? If latter, then I assume xml-conduit/stream is the baseline with have today; or is that after you have made some improvements?

Of course 6x of both time and space is a big factor so ideally would use that…

There's `xeno/DOM` in your results which does very well. You also have to remember that `hexml` is mostly written in C which means the memory usage is not tracked by GHC: the memory actually used is likely much higher than `weigh` is telling us unless it's doing some magic I'm not aware of. Is there a reason why you're not considering it? Perhaps it has fewer limitations than `hexml`, saving work.

**Comment by qrilka** [comment]
Mmm, I'm not sure what improvements you mean @Fuuzetsu 
Parsing code is quite basic - see https://github.com/qrilka/sheet-parsing-tests but it's the main part where xlsx parsing is done.
Regarding `xeno` - currently it doesn't work well with XML prologue - it's mentioned in tests repo README. I wanted to fix it (to make it work like `hexml` does) but didn't manage that yet and also @ocramz who is current `xeno` maintainer doesn't seem to react to github issues about `xeno`.

**Comment by ocramz** [comment]
Hi @qrilka , didn't have much time for this as of late, but I'm always fine with reviewing and merging patches

**Comment by qrilka** [comment]
oh that's great to hear @ocramz thanks

**Comment by qrilka** [comment]
So the current result for that 6000 x 26 file above looks like:
```
benchmarking readFile/with xlsx
time                 4.590 s    (4.414 s .. 4.802 s)
                     1.000 R²   (0.999 R² .. 1.000 R²)
mean                 4.663 s    (4.631 s .. 4.688 s)
std dev              37.02 ms   (0.0 s .. 41.88 ms)
variance introduced by outliers: 19% (moderately inflated)
             
benchmarking readFile/with xlsx fast
time                 719.7 ms   (718.1 ms .. NaN s)
                     1.000 R²   (1.000 R² .. 1.000 R²)
mean                 724.3 ms   (723.4 ms .. 725.2 ms)
std dev              1.525 ms   (0.0 s .. 1.532 ms)
variance introduced by outliers: 19% (moderately inflated)
```
which looks like we get 6x speedup from using `xeno` for parsing.
Actually that "fast" version is not yet 100% complete and parses only cells and row properties. But that part is more than 90% of all parsing for large sheets so adding other sheet details should not add much
