### ISSUE TITLE
List of Formatted

### ISSUE THREAD

**Issue by Anarchist666** [qrilka/xlsx#106]
The `Formatted` has `formattedCellMap` and `formattedStyleSheet` named fields. The `Xlsx` has `_xlSheets `(list of sheets) and `_xlStyles` (not a list) named fields.
If I has list of `Formatted`, how I can merge their `formattedStyleSheet :: StyleSheet` into one`_xlStyles :: Styles`?

**Comment by qrilka** [comment]
There is #83 about doing formatting on multiple sheets. See my last comment there.

**Comment by Anarchist666** [comment]
Thank you, chaining function work perfectly in my case. But, may be add `[StyleSheet] -> StyleSheet` function using `updateStyleSheetFromState` and `stateFromStyleSheet` eg?

**Comment by qrilka** [comment]
I'm not against adding some helper to format multiple sheets, probably just that `chaining` function just renamed to `formattedSheets`.
I'd be glad to get a PR.
But overall what about closing this issue and continue duscussion in #83 if you have more comments on the topic?
