### ISSUE TITLE
Large values in CellDouble are not correctly represented in generated xlsx file. 

### ISSUE THREAD

**Issue by dixie** [qrilka/xlsx#110]
Hello,
Thanks for useful library! 

It seems there is either a problem with large Double values or I misunderstood something. Values are somehow 'rounded' for example instead of 911090031.0 is in cell a value 910000000. 
I'm using xlsx 0.6.0.

See this example, in generated excel is value "910000000" :

{-# LANGUAGE OverloadedStrings #-}
module Write where
import Codec.Xlsx
import Control.Lens
import qualified Data.ByteString.Lazy as L
import Data.Time.Clock.POSIX

main :: IO ()
main = do
  ct <- getPOSIXTime
  let
      sheet = def & cellValueAt (1,2) ?~ CellDouble 911090031.0
       xlsx = def & atSheet "List1" ?~ sheet
  L.writeFile "example.xlsx" $ fromXlsx ct xlsx

**Comment by qrilka** [comment]
Thanks @dixie for your report - I'll look into it next week when I'll get back home from my vacation

**Comment by dixie** [comment]
Thanks for quick response, No problem. It seems this part of code is causing a touble:

txtd :: Double -> Text
txtd v | v - fromInteger (floor v) == 0 = toStrict . toLazyText $ formatRealFloat Generic (Just 0) v
       | otherwise = toStrict . toLazyText $ realFloat v

formatRealFloat and realFloat are functions from Data.Text.Lazy.Builder.RealFloat.

Behavior of that "integer branch" is following:
*Main Data.Text Data.Text.Lazy.Builder.RealFloat> formatRealFloat Generic (Just 0) 911090031.0
"9.1e8"

Behavior for other "number of decimal places to render"  parameters of formatRealFloat is following:

*Main Data.Text Data.Text.Lazy.Builder.RealFloat> Data.List.map (\i -> formatRealFloat Generic (Just i) 911090031.0) [0..10]

["9.1e8","9.1e8","9.11e8","9.111e8","9.1109e8","9.11090e8","9.110900e8","9.1109003e8","9.11090031e8","9.110900310e8","9.1109003100e8"]

I assume, that branch is supposed to create Integer String value (without .0). Maybe this could be an correction:

txtd :: Double -> Text
txtd v | v - fromInteger (floor v) == 0 = txti $ floor v
       | otherwise = toStrict . toLazyText $ realFloat v

**Comment by qrilka** [comment]
@dixie I think you're quite right  - do you want to create a PR?

**Comment by dixie** [comment]
@qrilka No, thank you. I don't have now a necessary configuration for git/github.

**Comment by qrilka** [comment]
Ok, no problem, will do that later today

**Comment by qrilka** [comment]
Fixed by e3774a62a0762affaa1129e9b83efdec372408a6
