### ISSUE TITLE
Do you have a working example that can produce pivot tables?

### ISSUE THREAD

**Issue by yugawara** [qrilka/xlsx#112]
Hi,
The xlsx file with a pivot table that I saved using this library won't open normally in Excel 2016. ( I haven't treid yet with any other version).  Although the file does open in the end after accepting recovery options, I get this error message:

Repaired Records: PivotTable report from /xl/pivotCache/pivotCacheDefinition1.xml part (PivotTable cache)

I am trying to create an Excel worksheet that contains a pivot table.  Do you have a working example?

**Comment by qrilka** [comment]
HI @yugawara 
Could you share your code maybe?
Actually  I planned to add something like "examples" directory for different xlsx features.
As for pivot tables - it looks like something's incorrect my test file - https://gist.github.com/qrilka/0f11a6220db6e263a6c539bff2f8fd04 fails with Excel Online.
I'll look into it - previously pivot tables were loading well with Excel.

**Comment by yugawara** [comment]
Hi Thanks for the quick reply!

 

Let me attach the sample program that recreates the problem.

**Comment by yugawara** [comment]
Hi, the attachment in the original email didn't work so I updated the comment above.   The link to the zip file is: [xlsxpivot.zip](https://github.com/qrilka/xlsx/files/1693551/xlsxpivot.zip)

**Comment by qrilka** [comment]
hi @yugawara 
Sorry for such a late reply
I can share a valid code example - https://gist.github.com/qrilka/a4a7bca9cbfc918083e72b5c5a48f835
I'll check out your code

**Comment by qrilka** [comment]
I think I have found a problem - it looks like integer values in pivot tables need some special treatment, I'll try to get a fix for it, otherwise your code looks OK

**Comment by qrilka** [comment]
@yugawara 0553914440aac750ee8ccff92ee1008750de7936 fixes problem with integers, please let me know if it works for you, otherwise I think we could close this ticket

**Comment by qrilka** [comment]
Closing as fixed, feel free to open more issues if you stumble upon anything @yugawara
