### ISSUE TITLE
Richtext cell: single underlining in sharedstrings not recognized

### ISSUE THREAD

**Issue by dvekeman** [qrilka/xlsx#122]
Hi

If I have a simple xlsx file with just one cell containing a single and double underline then only the double underline is recognized.
In case of a more complex xlsx file, things get structured differently and there it seems to behave correctly.

An example:

excel:
*A1*
```
Single | Double underline
------   =====
```

sharedstrings.xml

```
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<sst xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main" count="1" uniqueCount="1">
  <si>
    <r>
      <rPr>
        <u/>
...
      </rPr>
      <t>Single</t>
    </r>
...
    <r>
      <rPr>
        <u val="double"/>
...
      </rPr>
      <t>Double</t>
    </r>
...
  </si>
</sst>
```

Note: I haven't checked the specs as to whether my version of excel actually wrongfully encodes `<u />` instead of `<u val="single" />`

**Comment by qrilka** [comment]
Somewhat related to #69 - probably there are some other attributes with default values.
