### ISSUE TITLE
Support lens v5.1

### ISSUE THREAD

**Issue by prikhi** [qrilka/xlsx#151]
Hi, this package has dropped out of stackage nightly due to the release of lens v5.1. Can we get the version-bounds bumped for this package?

https://github.com/commercialhaskell/stackage/issues/6486

**Comment by qrilka** [comment]
With streaming added and `xeno` fixed there should be a new release - I will try to find time for this, thanks for reporting

**Comment by qrilka** [comment]
version 1.0.0 is released on Hackage

**Comment by prikhi** [comment]
Thanks, I think for inclusion into stackage, we need to add `data/inline-strings.xlsx` to the `extra-source-files` block in the cabal file. I get this when trying to run stackage's `verify-package` script:

```sh
$ ./verify-package xlsx
... build output ...
xlsx                             > test (suite: data-test)

Tests
... passing tests ...
  Stream tests
    Reader/inline strings
      Can parse row with inline strings:                             FAIL
        Exception: /home/prikhi/Projects/git/stackage/tmp.z6Wt/xlsx-1.0.0/data/inline-strings.xlsx: withBinaryFile: does not exist (No such file or directory)
        Use -p '/Can parse row with inline strings/' to rerun this test only.

1 out of 40 tests failed (2.20s)

```
