### ISSUE TITLE
Hackage docs are broken

### ISSUE THREAD

**Issue by santiweight** [qrilka/xlsx#153]
The docs worked for version 0.8.4:

https://hackage.haskell.org/package/xlsx-0.8.4

but do not work for version 1.0.0.x:

https://hackage.haskell.org/package/xlsx-1.0.0

**Comment by qrilka** [comment]
Please report this to Hackage maintainers, I have no idea how to debug their build failures

**Comment by jappeace** [comment]
you can upload by hand with something like:

```
	cabal new-haddock all --haddock-for-hackage --haddock-option=--hyperlinked-source
	cabal upload -d --publish ./dist-newstyle/*-docs.tar.gz
```

Needs to be done by a maintainer though.

**Comment by qrilka** [comment]
@jappeace I have heard about this workaround but I think the problem could be about https://hackage.haskell.org/package/bzlib-conduit not having `pkgconfig-depends` specified but I'm not sure how to test this hypothesis.
That won't trigger haddocks rebuild though so probably I still need to use the workaround

**Comment by qrilka** [comment]
You could ask Michael to checkout PR in https://github.com/snoyberg/bzlib-conduit
But I could test out with `xlsx` of course, I just don't think that it's where this should be fixed

**Comment by jappeace** [comment]
I've a cunning plan, I'll rename respective packages in the cabal files so I can make my own candidates to debug

**Comment by qrilka** [comment]
hi @jappeace did you have any success with your idea?

**Comment by jappeace** [comment]
well, yes I got it building here: https://hackage.haskell.org/package/bzlib-conduit-jappie
but I asked on [discourse](https://discourse.haskell.org/t/how-to-debug-matrix-ci-failures/4420), and they told me to make an issue on hackage-server repository: https://github.com/haskell/hackage-server/issues/1064

**Comment by qrilka** [comment]
I've uploaded haddocks to Hackage and closing this one in favor of haskell/hackage-server#1064
Thanks @jappeace for your help
