### ISSUE TITLE
Request: Minimal working example for styles

### ISSUE THREAD

**Issue by deemp** [qrilka/xlsx#166]
Hello! I'm trying to apply styles to my worksheet. I made an example, but I can't set a color for a cell.

https://gist.github.com/deemp/4d3fafd3885e9846814bf87287466d5f

Could you please provide a minimal working example with colors?

**Comment by qrilka** [comment]
Please take a look at this thing - https://gist.github.com/qrilka/ffd9fe984e3a50fa1b0bb6c5bcd7859c
xlsx is sometimes a bit odd, for example - take a look at the definition of `minimalStyleSheet `, you need to have some defaults in your stylesheet, and the main thing is using foreground color for a pattern not a background one.

**Comment by deemp** [comment]
@qrilka, thank you so much! When running your example, I got (3, 2) painted grey. This behavior should be related to this [issue](https://github.com/qrilka/xlsx/issues/73#issuecomment-317921350).

**Comment by qrilka** [comment]
PR will be more than welcome if you could find out the details behind this behavior
