### ISSUE TITLE
Perhaps move Lens functions to a separate package?

### ISSUE THREAD

**Issue by danchoi** [qrilka/xlsx#18]
Including the lens library brings in a lot of dependencies and makes the package brittle to build. 

I looked a the functions and types, and it seems that a base library that excludes lens would still be very useable, with lens only adding additional convenience functions. 

Would it make sense for a more minimal base package that excludes lens, and then another package that adds lens functionality?

This kind of separation is also followed by Data.Aeson (aeson) and Data.Aeson.Lens (aeson-lens).

**Comment by qrilka** [comment]
@danchoi do you still want this to be done? Almost a year passed already and for myself I don't see much motivation to remove `lens` dependency. Please raise your voice - otherwise I'll close this issue tomorrow

**Comment by danchoi** [comment]
Go ahead an close. I don't think I have time either, but I'll let you know if I manage to do it. Thank you for writing the library.
