### ISSUE TITLE
Use (x,y) coordinates instead of (y,x)

### ISSUE THREAD

**Issue by HalosGhost** [qrilka/xlsx#26]
Even cell names in Excel itself are referred to using ``(x,y)`` (though it uses a slimmed down syntax and substitutes letters for numbers in the ``x`` coordinate).

On a cartesian plane (or anything similar), everyone is taught always that coordinates will be of the form ``(x,y)`` where ``x`` is the “run” and ``y`` is the “rise”. There are only a few cases out there which are exceptions; in fact, I can only think of two: this library and ncurses.

This would be a massive API change (so, I expect it would be for the next release or further down the road), but it would certainly be a good one to make in my humble opinion.

**Comment by qrilka** [comment]
Actually Excel has 2 formats - both `(x,y)` and `(y,x)` :)
Though the second one (RC or row-column format) is not very widely known.
And yet I like your idea as ordinary x-y format is a bit more intuitive and put it into 0.2 (probably dumping streaming to some further release) but also some very large warning will be needed about such change :)

**Comment by HalosGhost** [comment]
Wow, I had no idea that existed in Excel (that's bad and Microsoft should feel bad). Either way, I'm glad to hear that you're open to this. When I stumbled upon that syntax in ncurses, it was a terrible revelation, but it's so widely used now that there's no way to change it.

**Comment by qrilka** [comment]
There are other opinions on that - I think Joel Spolsky in his "You suck at Excel" was showing that he uses RC format which is a bit more logical if you start looking into columns after the column Z :)

**Comment by HalosGhost** [comment]
Yeah, column-counting later on is cumbersome, but I think that says more about Excel itself than its users. For example, a really cool spreadsheet program called [Teapot](http://linux.maruhn.com/sec/teapot.html) foresook worksheets and lettered colums in favor of a true "3D" coordinate plane using a syntax like ``@(col,row,layer)`` where ``col``, ``row`` and ``layer`` are all 0-indexed integers.

Personally, I think that is one of the coolest ideas out there (and it offers some incredible advantages), but it never caught on and Teapot itself is now mostly not usable due to bitrot.

**Comment by edsko** [comment]
I don't have a very strong preference for either addressing format, but given that `(y,x)` is embedded in the library now, I'd be afraid it will cause lots of bugs in client code if you change it around. My vote is against.

**Comment by qrilka** [comment]
So I've decided just to add X-Y style accessors for those who could need them
