### ISSUE TITLE
Preserve Column Width formatting (in Parser and Writer)

### ISSUE THREAD

**Issue by HalosGhost** [qrilka/xlsx#27]
I have now gotten to the point where I am programmatically generating a ``.xlsx`` correctly using this library, which is a great start! Now, I am needing to set some column widths so that the spreadsheet displays sensibly on opening in Excel.

When I attempt to set the ``_wsColumns`` record field in my ``Xlsx``, everything compiles correctly and the ``.xlsx`` is created as-expected. However, when I open the file with Excel, I get the following error:

```
Excel found unreadable content in 'document_name.xlsx'. Do you want to recover the contents of this workbook? If you trust the source of this workbook, click Yes.
```

I assumed that I simply set the field incorrectly, so I took a copy of the file without the column data, opened it in Excel, set the column-widths to their correct sizes and saved it. I then attempted to parse in this corrected file to audit how it performed the column widths, but the ``_wsColumns`` record field for the read-in document is an empty list (which makes me think that the column width data was lost). Is this a bug in ``xlsx``'s writer/parser, a version incompatibility between the library and the version of Excel I am using (Office Pro 2010), or just a failure on my part to set the field correctly?

Is there documentation somewhere (the haddocks seem a bit lacking) of a minimal working exampe for setting column widths?

**Comment by qrilka** [comment]
Probably a bug :)
Thanks for reporting it
I'll try to reproduce it later in the evening

**Comment by HalosGhost** [comment]
Great, thanks! I look forward to hearing what you find!

**Comment by qrilka** [comment]
it looks like I have only Excel 2013 at hand - it does not complain about a test workbook having columns set by `wsColumns .~ [ColumnsWidth 1 10 4.5 0]` but Open XML Productivity Tool complains about that `0` style marker, could you attach your file?

**Comment by HalosGhost** [comment]
I will create a test file similar to the one I had, and post it for you (either soon today or early tomorrow).

**Comment by qrilka** [comment]
and a test workbook from your Excel version also won't hurt :)

**Comment by qrilka** [comment]
thanks

**Comment by HalosGhost** [comment]
Well, I hate to be in this situation, but I can no longer recreate the case and I have no idea what could have caused it nor what I could have done that would have fixed it…

The good news is that I have it completely functional now… I am sorry to have bothered you without cause, and if it happens again, I will make sure to document my case more carefully ahead of time!

**Comment by qrilka** [comment]
Could you probably provide some good example with proper columns?
I think I had some example when I was starting to create this library but now I almost don't use it so real life example would be cool addition to library docs.
Thanks.

**Comment by HalosGhost** [comment]
Sure, I could try to throw one together for you.
