### ISSUE TITLE
Add support for creating stylesheets

### ISSUE THREAD

**Issue by edsko** [qrilka/xlsx#28]
I have this implemented in a branch in my fork (https://github.com/edsko/xlsx/blob/pr/create-styleSheets/src/Codec/Xlsx/StyleSheet.hs). Will submit a PR once I've tested this a bit more and used it in production. Opening this issue so that you know it's in the works.

**Comment by qrilka** [comment]
Thanks a lot, eager to get it in the lib :)

**Comment by hanjoosten** [comment]
Yes, I'm looking foreward to this PR too! In my project I need to be able to write .xlsx files that contain different cell types (String, Bool, Date etc.). Being able to colour different cells differently would be awsome too. 
Thanks in advance!

**Comment by edsko** [comment]
Will submit this soon. Meanwhile you can use my `dev` branch if you want to try it out.

**Comment by qrilka** [comment]
closed by #36
