### ISSUE TITLE
Add support for SheetViews

### ISSUE THREAD

**Issue by edsko** [qrilka/xlsx#31]
PR forthcoming for this as well.

(I'm submitting all these PRs in one go because I'm still polishing some of the code occassionally and don't want to bother you will a PR only then to subsequently send more PRs to change the code again.)

**Comment by qrilka** [comment]
no available branch yet?
what are those views about?

**Comment by edsko** [comment]
No, not yet. Later today. The views allow you to specify stuff like "keep these cells visible when scrolling"; see `sheetViews` in the spec (2nd edition, section 18.3.1.88, "sheetViews (Sheet Views)", p. 1884).

**Comment by qrilka** [comment]
oh, it's from the Excel itself, ok, thanks

**Comment by edsko** [comment]
Preliminary version available at https://github.com/edsko/xlsx/tree/pr/support-sheetviews

**Comment by qrilka** [comment]
closed by #36
