### ISSUE TITLE
Support setting print options 

### ISSUE THREAD

**Issue by edsko** [qrilka/xlsx#34]
Stuff like landscape and repeated rows/columns. Opening an issue only so that you know I'm working on this; PR to follow.

**Comment by edsko** [comment]
Repeated rows/columns implemented by #35. Page setup implemented in https://github.com/edsko/xlsx/tree/pr/support-pagesetup. PR for all this stuff hopefully to follow before the week's end.

**Comment by qrilka** [comment]
closed by #36
