### ISSUE TITLE
Documentation of xlsx isn't generated on Hackage

### ISSUE THREAD

**Issue by hanjoosten** [qrilka/xlsx#39]
On hackage, xlsx does not build correctly because of tab characters in the source files. See [this log](http://hackage.haskell.org/package/xlsx-0.1.2/reports/2) for the details.

**Comment by qrilka** [comment]
I see failure because of failed installation of `semigroupoids` and warnings from `binary-search` package.
All of that has not much to do with the package.
Or please explain me where I am wrong assuming this.

**Comment by hanjoosten** [comment]
The reason I opened this issue is that hackage failed to generate the documentation of xlsx. I didn't look well enough, so I thought it was due to the tabs. 

I agree that semigroupoids fails to build for xlsx. This is strange, because semigroupoids does [build correctly on hackage](https://hackage.haskell.org/package/semigroupoids-5.0.0.4). 

Looking better at the log, it says:

``` 
Configuring semigroupoids-5.0.0.4...
setup: The following package dependencies were requested
--dependency='base-orphans=base-orphans-0.4.4-61f87fbe40b70a96b4f01742198bd89e'
however the given installed package instance does not exist.
Failed to install semigroupoids-5.0.0.4
```

However, looking at the other log, it says:

``` 
Downloading xlsx-0.1.2...
Configuring xlsx-0.1.2...
cabal: The following installed packages are broken because other packages they
depend on are missing. These broken packages must be rebuilt before they can
be used.
package conduit-extra-1.1.9.1 is broken due to missing package
attoparsec-0.13.0.1-6c1dca7c91cf58666f0446be739f1fb6
package xml-conduit-1.3.2 is broken due to missing package
attoparsec-0.13.0.1-6c1dca7c91cf58666f0446be739f1fb6
Failed to install xlsx-0.1.2
cabal: Error: some packages failed to install:
xlsx-0.1.2 failed during the configure step. The exception was:
ExitFailure 1
``` 

This suggests that conduit-extra-1.1.9.1 is broken, but it isn't, as you can see [here](https://hackage.haskell.org/package/conduit-extra-1.1.9.1)
I wonder if it is possible to get the documentation of xlsx right on hackage.

**Comment by qrilka** [comment]
The first failure from the last log talks about
```
ghc: can't find a package database at /home/builder/hackage-server/build-cache/tmp-install/packages.db
Failed to install dlist-0.7.1.2
```
So I'd suppose that it's something with package building on hackage itself. As for me I don't have much knowledge about it so I'm not sure how could I help here.
I think there was a way just to upload haddocks, that could at least add the documenation.

**Comment by qrilka** [comment]
It looks that it was some temporary hackage problem, the last version 0.2.1 has haddocs
