### ISSUE TITLE
Strange ordering in rows/cells

### ISSUE THREAD

**Issue by hanjoosten** [qrilka/xlsx#45]
In [Ampersand](https://github.com/AmpersandTarski/ampersand) we gratefully use xlsx to import information from Excel sheets. One in a while however, we get [strange results](https://github.com/AmpersandTarski/ampersand/issues/355). 

During diagnosis, I have discovered that reading excel sheets contains a bug. I have stripped an excel sheet to get a tiny example of a sheet that has this bug:

[ExcelBug.xlsx](https://github.com/qrilka/xlsx/files/204003/ExcelBug.xlsx)

If I run the following haskell, the strange behaviour appears:

```.haskell
{-# LANGUAGE OverloadedStrings #-}
module Main where
import Codec.Xlsx
import qualified Data.ByteString.Lazy as L
import Control.Lens

main :: IO ()
main = do
  bs <- L.readFile "ExcelBug.xlsx"
   
  let value = toXlsx bs ^? ixSheet "Handelingen" .
              ixCell (3,2) . cellValue . _Just
  putStrLn $ "Cell B3 contains " ++ show value

```

As a result, I get: ```Cell B3 contains Just (CellText "55555")```

As you can see in the excel sheet, cell B3 contains `programmeren; coordineren`.

This obviously is wrong.

**Comment by qrilka** [comment]
Hello @hanjoosten 
Thanks for reporting this - my tests show that it seems to come from the problem fixed in #44 - I will release new library version this evening, sorry for not doing that earlier

**Comment by hanjoosten** [comment]
Great! I'm looking foreward to the release. Thanks! I'll let you know if this solves my issues too.

**Comment by qrilka** [comment]
meanwhile you could checkout the version from the master if you have time for it

**Comment by qrilka** [comment]
New version is on hackage

**Comment by hanjoosten** [comment]
Tested and confirmed. Thanks!
