### ISSUE TITLE
Support cell comments and cell formulas.

### ISSUE THREAD

**Issue by gmachine1** [qrilka/xlsx#46]
I would like Cell to have two additional attributes: comment and formula. I need this for a project I am working on, and I am reading the code to figure how to implement them myself. If you could briefly describe how to go about adding these, that would save me much time. I hope to have this by Tuesday, April 26th, so if this is a simple change that you could complete by then, even better!

Thanks!

**Comment by gmachine1** [comment]
I believe I see how to support comments. In fromXlsx, generate and add an XML file for the comments, and in toXlsx, parse that XML file. I'll implement that.

**Comment by qrilka** [comment]
hi @gmachine1 
thanks for you interest in this library
and about comments - have you seen item 18.7 "Comments" in Ecma OOXML Part 1 spec?
And rnc schemas give good overview of XMLs, also be aware of the fact that relationship file seems to be needed (mapping worksheet to comments file), for that please check Part 2 of the spec, let me know how could I help you with implementing comments support.
BTW do you want to read comments or read and write too?

**Comment by qrilka** [comment]
Hi @gmachine1 did you have any success with this? I was thinking about adding that feature but if you have some code - I'd be glad to use it

**Comment by gmachine1** [comment]
Hi @qrilka I worked on it a bit and then stopped, because my contract from the company for which I was doing this had ended and was not continued. I sent them the code I had written for this, and they said they will try to finish it off. If you like, I can ask them to get in contact with you.

**Comment by qrilka** [comment]
If it's not a problem - please do, thanks

**Comment by qrilka** [comment]
I've created https://github.com/qrilka/xlsx/tree/comments to resolve comments topic - parsing is done and writing comments is in the works

**Comment by qrilka** [comment]
Regarding cell formulas there is #13 though it talks only about reading them (but could be reformulated)
