### ISSUE TITLE
Reading/writing images

### ISSUE THREAD

**Issue by ooblahman** [qrilka/xlsx#47]
Would be wonderful to have a function which takes an image (FilePath) and embeds it in the xlsx, such that it is visible when opened by Excel. The function signature might look something like 
```
addImage :: FilePath - > Dimensions -> Worksheet -> Worksheet
```
My understanding is that this image would be stored as a separate file in the xlsx, then referenced by pathname in the document XML. Ideally, there would also be functionality for reading images from an existing XLS? That is, the inverse function 
```
retrieveImages :: Worksheet -> [(FilePath, Dimensions)]
```

**Comment by qrilka** [comment]
Hi @ooblahman I have looked into the spec and it looks that the situation is a bit more complex that you describe (though not that much if we take only images into consideration).
Images are inserted using Drawing ML part of the spec and particularly for xlsx using `SpreadsheetML Drawing` part of it (see section 20.5)
So a worksheet could have some drawings in it which are stored in separate xml files and images are specified by `pic` element of a drawing file with a `blip` element inside of it referencing some particular image file.
So as I understand it I will add `_wsDrawings` to `Worsheet` type supporting only reading and writing pictures (and also adding some data structures for anchors etc).
Does it sound OK?
Also it looks like #49 needs to be resolved as this ticket needs even 2 new relations to be added

**Comment by qrilka** [comment]
I will close this one after merging https://github.com/qrilka/xlsx/pull/60 and #61 is the continuation of this one
