### ISSUE TITLE
Default values from the spec

### ISSUE THREAD

**Issue by vesten** [qrilka/xlsx#54]
Reading through the spec I found some default values that don't agree with those in StyleSheet.hs. I seem to be able to rationalize all but the Font defaults - they seem to not agree with empirical evidence. Please see my notes, [notes.txt](https://github.com/qrilka/xlsx/files/348746/notes.txt).

Further, I wonder if it might be worth considering modeling the record fields with default values without a Maybe type? Perhaps the parser could insert the proper default value upon detecting the missing tag.

**Comment by qrilka** [comment]
hi @vesten 
yes, there is a "problem" with those values having defaults.
your file doesn't quite describe what do you see as wrong - could you be more specific?
As for the getting rid of `Maybe` - I'd like to but that just doesn't work at least "out of the box".
In xml you could specify not just e.g. `False` and `True` but also combinations like `True` specified, `True` set by element by default, `False` set by lack of XML element, `False` set explicitly.
Actually `Maybe` * `Bool` doesn't cover all of the options :)
Probably the thing that keeps me from removing `Maybe` wrapper from `Bool` with default `True` is my worry that some weird case from MS could require something like that.
But probably that could be resolved when somebody will get bitten by it.
Do you want to create a PR covering those bools at least?

**Comment by vesten** [comment]
Hi @qrilka 
A PR is no problem (#55), though I rather clumsily didn't pay enough attention to how I based by changes. The only deltas that matter are the Default instances near the bottom of StyleSheet.hs. 

Also, there was nothing wrong per se. I only noticed the spec sporadically offered default values and the Default instances in StyleSheet.hs uniformly declared 'Nothing' as the default. I wasn't sure if this was intentional and served another purpose.

And you're right about keeping the Maybe values in general. As I look again, a default value is given for the attribute not the tag. If the tag is missing the spec offers no information regarding a value, with the exception of the boolean elements of the Font type were the spec adds the verbiage "If omitted, the default value is true ". Ref:  18.8.2 b (Bold)   p. 1757, 
            18.8.12  consense (Condense)  p. 1764,
            18.8.17  extend (Extend)  p. 1766,
            etc.
