### ISSUE TITLE
Cannot parse an empty workbook

### ISSUE THREAD

**Issue by vesten** [qrilka/xlsx#62]
Creating a new workbook and saving as 'Book0.xlsx', then executing 

                toXlsx <$> Data.ByteString.Lazy.readFile "Book0.xlsx" 
in GHCi results in 

    *** Exception: MissingFile "xl/sharedStrings.xml"

[Book0.xlsx](https://github.com/qrilka/xlsx/files/415862/Book0.xlsx)

**Comment by qrilka** [comment]
Thanks @vesten, looks like too tight constraint was used, I will look into it later today.
How critical is it for you? Last changes in `Formatted` make me think about version `0.3.0` already and I wanted to push a bit more changes into it maybe :)

**Comment by vesten** [comment]
No stress here. I can sit on v0.2.3 for a while. Thanks for asking though.

**Comment by qrilka** [comment]
Fixed by ecf9097]
