### ISSUE TITLE
Parsing minimal workbooks containing images results in exception

### ISSUE THREAD

**Issue by vesten** [qrilka/xlsx#63]
Converting any of the attached workbooks to an Xlsx type results in the exception,

          *** Exception: InvalidFile "xl/media/image.{gif,png,jpeg}"

In each case a single image file 'smiley.{gif, jpg, png}' was inserted to a newly created workbook and the file was saved.

[BookGif.xlsx](https://github.com/qrilka/xlsx/files/415948/BookGif.xlsx)
[BookJpg.xlsx](https://github.com/qrilka/xlsx/files/415950/BookJpg.xlsx)
[BookPng.xlsx](https://github.com/qrilka/xlsx/files/415949/BookPng.xlsx)

**Comment by qrilka** [comment]
Ouch once again :)

**Comment by qrilka** [comment]
@vesten how did you put images into those files? Using Excel, right?

**Comment by vesten** [comment]
Yes, from Excel. Insert menu, Picture icon on ribbon bar. FWIW, Office Prof Plus 2010 at work.

**Comment by qrilka** [comment]
Thanks

**Comment by qrilka** [comment]
@vesten could you try out the last `develop`? 51d886dfddb7e1f67de181139525a10627b7ec07 should fix this problem

**Comment by vesten** [comment]
Yup, that does it. Verified issue #62 & #63. Many thanks @qrilka.
