### ISSUE TITLE
library cannot parse comment created by libreoffice calc

### ISSUE THREAD

**Issue by Shimuuar** [qrilka/xlsx#68]
Attempt to parse XLSX file with comment which was created by libreoffcie 5.2.3 (from debian testing) results in 

```
testcase: Safe.fromJustNote Nothing, authorId                                                                                         
CallStack (from HasCallStack):                                                                                                        
  error, called at ./Safe/Util.hs:18:44 in safe-0.3.9-61ab156570e2b884f7dd8f14bc7f08646c0c1ff9b7315fb92c2ac7d05ee27df0:Safe.Util
```

Here is file which triggers bug. Simply a single cell with comment
[testcase2..xlsx](https://github.com/qrilka/xlsx/files/616372/testcase2.xlsx)

**Comment by qrilka** [comment]
Ouch, thanks for the report.
I think `authorId` was mentioned as required in the spec - I'll take a look later today.

**Comment by qrilka** [comment]
Unfortunately no hackage release yet - I'd like to finish pivot tables to make a new major release

**Comment by Shimuuar** [comment]
Not a problem. It's not urgent and I can always use version from git if I need it

Thank you!
