### ISSUE TITLE
write file example to be repaired (Windows)

### ISSUE THREAD

**Issue by stla** [qrilka/xlsx#72]
Hello,

On Windows, using Microsoft Excel 2010, this is what I get when I run [this example](https://hackage.haskell.org/package/xlsx-0.4.0/docs/Codec-Xlsx.html) and open the file:

![capture1](https://cloud.githubusercontent.com/assets/4466543/21470577/a0607e3e-ca8f-11e6-820b-471fd6f62af5.PNG)

![capture2](https://cloud.githubusercontent.com/assets/4466543/21470579/a9c7b92e-ca8f-11e6-90e7-bad1eb9b0a8e.PNG)

```
<?xml version="1.0" encoding="UTF-8" standalone="true"?>

-<recoveryLog xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main">

<logFileName>error027600_01.xml</logFileName>

<summary>Errors were detected in file 'C:\HaskellProjects\test_xlsx\example2.xlsx'</summary>


-<repairedParts summary="Following is a list of repairs:">

<repairedPart>Repaired Part: /xl/workbook.xml part with XML error. (Workbook) Catastrophic failure Line 1, column 323.</repairedPart>

<repairedPart>Repaired Part: /xl/worksheets/sheet1.xml part with XML error. Catastrophic failure Line 1, column 517.</repairedPart>

</repairedParts>

</recoveryLog>
```

**Comment by qrilka** [comment]
Thanks for reporting - I'll work on it

**Comment by stla** [comment]
Do you know the xlsx file ? I could send it to you.

**Comment by qrilka** [comment]
Sure I can recreate one but please sent yours just to be sure that we talk about the same thing, thanks.

**Comment by stla** [comment]
Ok, I've just sent it to your gmail adress.

**Comment by qrilka** [comment]
hi @stla sorry for being slow - first it was my vacation then some virus hit me :-\
please check out bc08532 which is already in `master` - if the result looks OK then I'll release it as `0.4.1`
Thanks

**Comment by stla** [comment]
I have to install the package from github ? I'm not sure I will be able to do that, but I'll try.

**Comment by qrilka** [comment]
@stla do you use `stack`?
with it it's just about adding
```
- location:
    git: https://github.com/qrilka/xlsx.git
    commit: bc0853209ee3a0a0f6749252f4802eebaf67a014
  extra-dep: true
```
to your `stack.yaml`

**Comment by stla** [comment]
I have `stack´, but for testing your package I'm using `cabal`. Do you know how to do with `cabal`?

**Comment by qrilka** [comment]
I don't use `cabal` for quite some time already as there is `stack` giving more convenient interface.
You could test using the following scenario:
1. `git clone git@github.com:qrilka/xlsx.git`
2. `cd xlsx`
3. `cabal sandbox init`
4. `cabal install`
5. create a file `testHaddocks.hs` with test code:
```
{-# LANGUAGE OverloadedStrings #-}
module TestHaddocks where
import Codec.Xlsx
import Control.Lens
import qualified Data.ByteString.Lazy as L
import Data.Time.Clock.POSIX

main :: IO ()
main = do
  ct <- getPOSIXTime
  let
      sheet = def & cellValueAt (1,2) ?~ CellDouble 42.0
                  & cellValueAt (3,2) ?~ CellText "foo"
      xlsx = def & atSheet "List1" ?~ sheet
  L.writeFile "example.xlsx" $ fromXlsx ct xlsx
```
6. `cabal exec runhaskell testHaddocks.hs`
7. check `example.xlsx` which you'll receive on the previous step

**Comment by stla** [comment]
I've managed to install. And yes, the problem has gone - the xlsx file is good !

**Comment by qrilka** [comment]
Released as https://github.com/qrilka/xlsx/tree/0.4.1
