### ISSUE TITLE
Replace <variant> with <vt:variant> ?

### ISSUE THREAD

**Issue by stla** [qrilka/xlsx#74]
Hello, 

 The XLSX files created by the `xlsx` library cannot be read by the Javascript library [js-xlsx](https://github.com/SheetJS/js-xlsx) nor by the R package [readxl](https://github.com/hadley/readxl). The first one returns an error, the second one returns an error or totally crashes R.

 I don't know the cause for `readxl`. I investigated a bit what happens with `js-xlsx`, and I found that it is looking for XML tags `<vt:variant>...</vt:variant>` while `xlsx` creates tags `<variant>....</variant>`. Maybe it needs `vt:vector` instead of `vector` as well.

**Comment by qrilka** [comment]
That means that those packages can't read XML properly :)
`vt` is just a namespace prefix and it could be any string as far as it refers to a correct namespace.
But we could use "default" prefixes (and we do in some XMLs but not in every one of them).
Having more concrete errors could help a lot

**Comment by stla** [comment]
That's the first time I get a problem with these packages. That shows that when I create a file with Excel (2010), it creates the `vt:` tags.

**Comment by stla** [comment]
I gonna try to replace the tags in order to see whether this is the only problem. Too sad if we can't use `readxl` !

**Comment by stla** [comment]
I've done it. In the file `app.xml`, I added the prefix `vt:` to `variant`, `vector`, `lpstr` and `i4`. Then `js-xlsx` correctly reads the file. But `readxl` still doesn't work. Maybe I will talk about that to @hadley.

**Comment by stla** [comment]
I've found the problem: `readxl` crashes when the 0-th CellXf has no number format id !

**Comment by stla** [comment]
I close since one can set a number format id with `xlsx` and then `readxl` works.

You're right about the `vt:`, this is an issue for `js-xlsx`.
