### ISSUE TITLE
cwStyle causes an Excel repair

### ISSUE THREAD

**Issue by stla** [qrilka/xlsx#75]
Hello, 

 I tried to set column widths. The field `cwStyle` is mandatory. I don't know what it refers to. I set it to 1, so that I got
```
	<cols>
		<col max="4" min="1" style="1" width="30"/>
	</cols>
```
in my `sheet1.xml`. Excel does not like that, it has to repair the file:

```
Repaired Records: Column information from /xl/worksheets/sheet1.xml part
```

I took a look at the repaired file. Excel did several modifications but the important one is that it removed the `style="1"`. Indeed, if I remove it:

```
	<cols>
		<col max="4" min="1" width="30"/>
	</cols>
```

then Excel opens the file without issue.

**Comment by qrilka** [comment]
Thanks for reporting - I'll look into it later today

**Comment by qrilka** [comment]
@stla it appears to be a bug as `style` is optional having default value of `0`. Spec says only
```
Default style for the affected column(s). Affects cells not yet allocated in the column(s).
In other words, this style applies to new columns.
The possible values for this attribute are defined by the W3C XML Schema unsignedInt
datatype.
```
I.e. they don't say directly that it's the same "pointer" into cellXfs as for cells but I suppose it is so.
And also this default of `0` could be some kind of explanation for #73

**Comment by qrilka** [comment]
@stla please let me know if  f607a6f looks enough to close this issue

**Comment by stla** [comment]
So, without using your update, I tried and I confirm it works with: 
```
ColumnsWidth {cwMin = 1,
                          cwMax = ncols,
                          cwWidth = 30,
                          cwStyle = 0}
```
(previously I set `cwStyle=1`). 

What is your update supposed to do ? To fix if `cwstyle` is mispecified ?

**Comment by stla** [comment]
I tried your new version. With `cwStyle=1` there's the same problem. But I probably misunderstood what I'm supposed to try.

**Comment by qrilka** [comment]
With the update you shouldn't be able to set `cwStyle=1` as the field type now is `Maybe Int`.
I.e. the update was about being able to set it to `Nothing`. From the other side as I understand it should work with `cwStyle=Just 1` if you'll add new `cellXf` record (which should get id `1`)

**Comment by stla** [comment]
Are you sure ? I'll look later, but I'm pretty sure that I had `cwStyle :: Int` yesterday. I have your update since there is now a field `AutoFilter` in `Worksheet`.

**Comment by qrilka** [comment]
I've referenced incorrect commit but https://github.com/qrilka/xlsx/commit/61e41a9e6a14324a7a0c2e123789631e3f39381a#diff-47e033d4407f05d43c094884d7c4194fR145 shows what I had in mind:
```
  , cwStyle :: Maybe Int
```

**Comment by stla** [comment]
I do that but stack does not update:
```
- location:
   git: https://github.com/qrilka/xlsx.git
   commit: 61e41a9e6a14324a7a0c2e123789631e3f39381a
```
I don't understand. This is the way I used yesterday.

**Comment by stla** [comment]
Ok, I've used `git clone` and I replaced the previous download. It works with `cwStyle = Nothing`. Thank you !
