### ISSUE TITLE
Generic instances

### ISSUE THREAD

**Issue by taktoa** [qrilka/xlsx#81]
It would be nice if we could have `Generic` instances for all the datatypes in this library. This would make it easier for people using the library to define orphan instances (e.g.: for serialization).

In particular this would be useful because sometimes this library takes a long time (and a lot of memory) to parse large spreadsheets, so for development purposes I like to parse the spreadsheet and then serialize it to the disk, and then deserialize it every time I `:r` in GHCi. Here's the file I had to write to do this: [gist](https://gist.github.com/taktoa/b68981ef5c10a92ea48eaa24cbeef9df).

You may also consider providing serialization instances (any of the standard libraries, `binary`/`cereal`/ `store`, should work) in this library proper, to enable such a workflow.

BTW: It is also often useful from an end-user perspective to provide instances of `Data` and `NFData` whenever possible. `Generic` is really an essential one though.

**Comment by qrilka** [comment]
@taktoa could you create a PR with those instances?
Regarding `binary` / `cereal` / `store` I don't think there is a high motivation to add an extra dependency and enlarge library build time so I'd prefer not to do that.
And regarding resource consumption - the library was never optimized from this point of view so if you have any good test cases it makes sense at least to explore them.

**Comment by qrilka** [comment]
But also deriving typeclasses has some costs - https://twitter.com/taylorfausak/status/860347854413598721

**Comment by taktoa** [comment]
Oops, almost forgot about this. Check out PR #84.

**Comment by qrilka** [comment]
Resolved by #84
