### ISSUE TITLE
Does FontFamily works ?

### ISSUE THREAD

**Issue by stla** [qrilka/xlsx#85]
Hello, 

 I have the `FormattedCell` below, with `_fontFamily = Just FontFamilyDecorative`, but when I write the xlsx, there's no special rendering. Is it expected ? (I don't know what I'm supposed to see, actually).

`FormattedCell {_formattedCell = Cell {_cellStyle = Nothing, _cellValue = Just (CellText "abc"), _cellComment = Nothing, _cellFormula = Nothing}, _formattedFormat = Format {_formatAlignment = Nothing, _formatBorder = Nothing, _formatFill = Nothing, _formatFont = Just (Font {_fontBold = Nothing, _fontCharset = Nothing, _fontColor = Nothing, _fontCondense = Nothing, _fontExtend = Nothing, _fontFamily = Just FontFamilyDecorative, _fontItalic = Nothing, _fontName = Nothing, _fontOutline = Nothing, _fontScheme = Nothing, _fontShadow = Nothing, _fontStrikeThrough = Nothing, _fontSize = Nothing, _fontUnderline = Nothing, _fontVertAlign = Nothing}), _formatNumberFormat = Nothing, _formatProtection = Nothing, _formatPivotButton = Nothing, _formatQuotePrefix = Nothing}, _formattedColSpan = 1, _formattedRowSpan = 1}`

**Comment by qrilka** [comment]
xlsx options could be not quite what you expect from them - I don't know myself what's the point behind this one but I'll take a look at it tomorrow

**Comment by qrilka** [comment]
@stla it looks like that property is just some redundant information about fonts.
The spec isn't very specific:
```
The font family this font belongs to. The font name overrides when there are conflicting values.
```
I don't know why could that be needed in xlsx. My only hypothesis is that it came just as some legacy from Excel implementation.

**Comment by qrilka** [comment]
@stla could I use this issue or there's something else which could be done about it?

**Comment by stla** [comment]
Yes, let's close.
In Excel there's nothing like "font family", that's weird.
Thanks.
