### ISSUE TITLE
ExitFailure 11 from cabal install xlsx on Mac OS X

### ISSUE THREAD

**Issue by dckc** [qrilka/xlsx#9]
I just installed the haskell platform on this MacBook (OS X 10.6.8) and ran `cabal install xlsx`. After 20 minutes or so, it failed. I can't make much sense of the diagnostics.

I captured the [full output](https://gist.github.com/dckc/5c0df274b11c72383f76).

Other relevant diagnostic info I can think of:

```
bash-3.2$ cabal --version
cabal-install version 1.16.0.2
using version 1.16.0 of the Cabal library 

bash-3.2$ ghc --version
The Glorious Glasgow Haskell Compilation System, version 7.6.3
```

**Comment by qrilka** [comment]
Closing as I have no Mac to recheck it and no other volunteers to do that
