### ISSUE TITLE
xlsx cannot parse file produced by google sheets

### ISSUE THREAD

**Issue by Shimuuar** [qrilka/xlsx#90]
It fails with error `InvalidFile`. Here is link to the file https://www.dropbox.com/s/i5b65fzf1roeebt/testcase.xlsx?dl=0

LibreOffice calc can open it successfully though

**Comment by qrilka** [comment]
Thanks @Shimuuar for reporting, I'll try to find some time to dig into it

**Comment by qrilka** [comment]
Fixed by 2f1e96f

**Comment by qrilka** [comment]
I guess it's time for a new release with these not quite backwards compatible changes
