### ISSUE TITLE
Not all conditional formatting rules are implemented

### ISSUE THREAD

**Issue by Shimuuar** [qrilka/xlsx#97]
Following conditional formatting rules are not implemented:

### Above/below Average
This conditional formatting rule highlights cells that are
above or below the average for all values in the range.

### Color Scale
This conditional formatting rule creates a gradated color scale   on the cells.

### Icon Set
This conditional formatting rule applies icons to cells according to their values.

### DataBar
This conditional formatting rule displays a gradated data bar in the range of cells.

### Duplicate Values
This conditional formatting rule highlights duplicated values.

### Unique Values

This conditional formatting rule highlights unique values in   the range.

### Top 10
This conditional formatting rule highlights cells whose values   fall in the top N or bottom N bracket, as specified.

**Comment by qrilka** [comment]
Resolved by 6fba02a08a90c57e25d31253221c8b06801bf73c
