### ISSUE TITLE
Support for import/export of filter 

### ISSUE THREAD

**Issue by Shimuuar** [qrilka/xlsx#98]
I'm speaking about this feature:

https://support.office.com/en-us/article/Filter-data-in-a-range-or-table-01832226-31b5-4568-8806-38c37dcc180e

**Comment by qrilka** [comment]
As far as I remember it was implemented in http://hackage.haskell.org/package/xlsx-0.6.0/docs/Codec-Xlsx-Types-AutoFilter.html
Please let me know if you see something missing (or maybe just implemented incorrectly)

**Comment by Shimuuar** [comment]
I missed that module somehow. But from cursory look it seems that it's not complete implementation. Judging by excel's menus it should be much more complicated. I'll come back tomorrow with more information

**Comment by qrilka** [comment]
@Shimuuar I think I implemented options which are (or were) available in Google Sheets

**Comment by Shimuuar** [comment]
I uploaded example file with all value-based filters supported by excel 2013. I think it would be nice to support them all

[filters_example.xlsx](https://github.com/qrilka/xlsx/files/1315211/filters_example.xlsx)

**Comment by qrilka** [comment]
Thanks

**Comment by qrilka** [comment]
Actually @Shimuuar it looks that almost all of those filters are already implemented. The only condition type from your file which is not yet present in the library is `dynamicFilter`. And the spec also contains definitions of filters `dateGroupItem`, `colorFilter`, `iconFilter` and `top10`. It you don't have any objections I'll try to get complete implementation

**Comment by Shimuuar** [comment]
@qrilka No objections at all

**Comment by qrilka** [comment]
Resolved in 25c0689d5a00b33f44c848f486d55deb6f5078b7
